### ISSUE TITLE
doesnt work on windows xp

### ISSUE THREAD

**Issue by ghost** [MRmlik12/Windows-Fetch#1]
![image](https://github.com/MRmlik12/Windows-Fetch/assets/127148610/46e6a659-5567-480f-bd6d-95893dca441b)

**Comment by maclightning2** [comment]
Runs on my version of XP build 2600.xpsp_sp3_qfe.180912-0606 (Media Center Edition with all possible updates installed and registry hack to enable embedded POS).

However crashes after reporting resolution successfully.

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
    at Windows_fetch.Resources.Diagnostic.DotNetVersion()
    at Windows_fetch.Show.Oldest()
    at Windows_fetch.Show.OnStart()
    at Windows_fetch.Program.Main(String[] args)
```

**Comment by alektronic** [comment]
> However crashes after reporting resolution successfully.
> 
> ```
> Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
>     at Windows_fetch.Resources.Diagnostic.DotNetVersion()
>     at Windows_fetch.Show.Oldest()
>     at Windows_fetch.Show.OnStart()
>     at Windows_fetch.Program.Main(String[] args)
> ```

I can report the same on XP SP3
